### ISSUE TITLE
Lua port?

### ISSUE THREAD

**Issue by micangl** [srcery-colors/srcery-vim#100]
@roosta I was thinking about making a lua port of srcery as a first plugin. But I wanted to ask your opinion, since I have some doubts:
1. Is there actually any demand for this?
2. Would you like for srcery to remain a single, cross-compatible plugin?
3. Would an eventual port officially become part of srcery-colors?

**Comment by roosta** [comment]
Hi @micangl, you can make it if you feel its needed, but what would a lua theme add that a cross platform could not?

1. You're the first person mentioning it.
2. Yes
3. Depends how cleanly it integrates.

**Comment by micangl** [comment]
This is why I was uncertain. Well, since there doesn't seem to be any actual necessity for such a port, I won't proceed.
