### ISSUE TITLE
Wrong highlighting in Telescope preview window

### ISSUE THREAD

**Issue by micangl** [srcery-colors/srcery-vim#101]
![nvim](https://github.com/srcery-colors/srcery-vim/assets/142919381/d2ee2747-4d8b-4eb7-af90-2aa9cae2385e)
As is seen the picture, the C function names in the preview panel shouldn't be using the `white` color, but the `bright-white` color.

**Comment by roosta** [comment]
Thanks for reporting @micangl, appreciate it. I don't use telescope myself but I did a quick google and the preview window seems to have a bit of complexity to it.

I'm busy over the weekend, but I'll take a look on Monday. If you figure out why that happens, feel free to open a PR.

**Comment by micangl** [comment]
This is related to #82: Vim's (and, by extension, Neovim's) c syntax file doesn't define functions highlight groups.
A solution is to create a personal syntax file which defines said groups. Another is to just use Tree-sitter.
