### ISSUE TITLE
Customizable xterm colors

### ISSUE THREAD

**Issue by McSinyx** [srcery-colors/srcery-vim#106]
It's nice that the 24-bit colors are customizable through globals.  I'm trying to override the color scheme with a light palette and while the 16 base colors are inherited from the terminal, the oranges and xgrays are pretty much hard coded: https://github.com/srcery-colors/srcery-vim/blob/8ea4c4f5caf61ac4ab887fc53eabc916985db881/autoload/srcery.vim#L192-L201

Are you open to supporting 8-bit color override?

**Comment by roosta** [comment]
Yeah, I'd be open to that. The only real problem that presents is that it would not work for terminals. If that's not a problem for you, I don't see why not to allow for overrides to the vim theme. It would create color disparity between the terminal and vim though.

**Comment by McSinyx** [comment]
The 24-bit (for e.g. GVim) and 8-bit (for Vim on XTerm and alike) colors
both need to be set IIUC.  While for former is configurable in Vim,
the latter takes after the terminal, and it's not conventional
to set colors 16 and above.

If the 8-bit oranges and xgrays are tweaked like following,
it actually works for me on light terminal themes:
https://trong.loang.net/~cnx/srcery-light/commit?id=406173468fb0

**Comment by roosta** [comment]
right right, I misunderstood your question. I for some reason figured the xterm colors weren't override-able even in 24bit but they of course are. What would be nice is if you could supply a list of hex and number as an override value, but that would be a breaking change for some people I'd expect. Some clean way around that while still preserving the old syntax would be ideal.

**Comment by McSinyx** [comment]
Since it does not make sense to override the first 16 8-bit colors, I suggest going with something like `srcery_xgray*_cterm` for the xgrays, oranges, teal and hard black.

**Comment by roosta** [comment]
Yeah, that would work, keep it simple n all. If you could add a PR that would be appreciated.
