### ISSUE TITLE
g:srcery_bg setting is not properly explained

### ISSUE THREAD

**Issue by Dorovich** [srcery-colors/srcery-vim#109]
Hi, i've just updated the plugin to the latest version through Vim-plug and noticed that `g:srcery_bg_passthrough` is no longer a thing now. I've tried setting the value of `g:srcery_bg` to `NONE` as the readme explains but errors keep showing up. Later after minutes of trial and error discovered that to achieve the same transparency as before it had to be set to `['NONE', 'NONE']`.

I feel like it could have been explained better in the plugin's readme or help files, since it is rather unintuitive for those who don't know much about vimscript!

Thanks for the awesome colorscheme :)

**Comment by roosta** [comment]
Fair point, I thought I explained it OK, but you're right. Any suggestions on how to word it?

**Comment by Dorovich** [comment]
Maybe something like this?

> **g:srcery_bg**
> 
> Default: `[g:srcery_black, 0]`
> 
> Let's you customize the background color. This var takes a list with two values, with a HEX in the first position, and a terminal color index for the second position. This lets you set both a 24-bit color, and a 8bit terminal color index.
> 
> You can specify `'NONE'` as one of the values to make it transparent, as such `['NONE', 'NONE']` would be the same as the previous option `g:srcery_bg_passthrough = 1`.
> 
> You can specify `'DEFAULT'` as one of the values in order to use that position's default value.

**Comment by roosta** [comment]
Thanks @Dorovich, I've updated the description in the readme and help file.
