### ISSUE TITLE
Rust operator highlight forces background color

### ISSUE THREAD

**Issue by flaamjab** [srcery-colors/srcery-vim#112]
I use [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) with neovim and have noticed that the background color of operator characters in the context box is wrong:

![image](https://github.com/srcery-colors/srcery-vim/assets/46999161/11716aa8-8487-49c5-894f-231225cf3e62)

Rust.vim over at neovim repository [links rustOperator to Operator](https://github.com/rust-lang/rust.vim/blob/889b9a7515db477f4cb6808bef1769e53493c578/syntax/rust.vim#L322C39-L322C39) which is itself linked to Normal [here](https://github.com/srcery-colors/srcery-vim/blob/d6037f87842753a85e4cd855a2ca4206ac04db7e/colors/srcery.vim#L306), which has background color set by default. So that probably explains why Rust operators in particular are colored incorrectly. I'm not sure if any other language has a similar issue, C and C++ seem to be alright.

Simply adding something like `hi! link rustOperator SrceryWhite`  in rust.vim makes it all look good.

So anyway, would be nice to have it tweaked. Cheers.

**Comment by MindTooth** [comment]
Hi,

Maybe the `rustOperator` should be set to `Operator`.  @roosta any recollection of this?

**Comment by roosta** [comment]
`Operator` already links to `Normal`, so I don't think that would solve the issue. I'm thinking linking `Operator` to `SrceryBrightWhite`. It gets overridden in some languages but as a general rule its supposed to be white like normal. There doesn't seem to be any reason to set the background color for the operator, and the `srcery_bg` option works fine as far as I can tell with that change.
