### ISSUE TITLE
No contrast on floating windows spawned by nvim-lspconfig

### ISSUE THREAD

**Issue by flaamjab** [srcery-colors/srcery-vim#115]
Hello!

The [latest commit](https://github.com/srcery-colors/srcery-vim/commit/2e9b1d46bf28cf390950c586d5d1c688a009c8ec) basically made floating windows have the same background as normal windows.

Before:
![2024-02-17T15:02:40](https://github.com/srcery-colors/srcery-vim/assets/46999161/8c5b8064-b441-4bad-8a42-3c2f680a641c)

Now:
![2024-02-17T15:02:55](https://github.com/srcery-colors/srcery-vim/assets/46999161/92b131dc-546f-4e86-8c0f-2143f7856919)

nvim-lspconfig by default only adds some padding to the floating window, so it becomes difficult to discern them from normal windows if they all have the same background.

In other colorschemes (gruvbox, rose-pine) floating windows have a visibly different background.

Was it the intention to change that?

**Comment by roosta** [comment]
No, I was worried about side effects. I'll revert the commit
