### ISSUE TITLE
Possible missing treesitter support for italic, bold, italic, underline and strikethrough

### ISSUE THREAD

**Issue by Sberlos** [srcery-colors/srcery-vim#117]
Hello,

first of all I would like to thank you for the amazing color scheme, it is my default one since many years on all my machines.

I am a neovim user and I started using the [neorg](https://github.com/nvim-neorg/neorg) plugin for note taking. This plugin has the possibility to style text as bold, italic, underline and strikethrough. Sadly, I discovered that those text decorations are not working with srcery. I opened the same file containing the decorations using the [kanagawa](https://github.com/rebelot/kanagawa.nvim) color scheme and they displayed correctly. This suggests me that the problem may be with srcery. I don't know much about color schemes in vim/neovim but I know that neorg uses Treesitter extensively and for this reason I suppose the lack of decorations is tied to the missing support of some part of it.

I don't know if it would be of any help, but neorg defines the highlighting of text decorations [here](https://github.com/nvim-neorg/neorg/blob/086891d396ac9fccd91faf1520f563b6eb9eb942/queries/norg/highlights.scm#L223) and they correspond on the values that I see in neovim when I invoke `:Inspect` on the corresponding decorated word.

For information, I am using neovim 0.9.5-2 and the latest version of both neorg and srcery. I am using srcery with the default configuration except for the `srcery_italic` variable which I have set to 1.

I understand that this might be a niche user-case and that you might not have neorg nor neovim installed and I would be happy to do anything to help identify the problem.

Thank you in advance!

**Comment by roosta** [comment]
Hi! Thanks for opening an issue, I was able to figure out why this wasn't working, and I have submitted a [PR](https://github.com/srcery-colors/srcery-vim/pull/118) with a fix. If you could try the branch and confirm it is working?
