### ISSUE TITLE
Italics not working in gnome-terminal

### ISSUE THREAD

**Issue by stove-panini** [srcery-colors/srcery-vim#25]
I'm using Vim 8.1 with Gnome Terminal 3.28.

While writing markdown and using a different colorscheme, italics appear properly. Srcery, with the proper option set (`let g:srcery_italic = 1`), will conceal the syntax but font does not italicize. Bold works, however.

Please let me know if I can provide any more information!

**Comment by MindTooth** [comment]
What distro?  I'll fire up a VM with your distro.

**Comment by stove-panini** [comment]
@roosta I had my options set after the colorscheme! Setting them before the declaration solved the problem. Thank you!

**Comment by roosta** [comment]
Glad to help. There really should be a note about that in the readme.
