### ISSUE TITLE
Cannot find color scheme 'srcery'

### ISSUE THREAD

**Issue by ngc2392** [srcery-colors/srcery-vim#28]
Hi, before I ask my question, I just wanted to say thanks for this color scheme.  I really like it!

My problem is that Vim can't find the color scheme.  I have just recently been trying to learn more about Vim, so this may just be an error due to my lack of experience with Vim.  

I am using vim-plug to install it.  According to :PlugStatus, srcery-vim is installed successfully.  Then, I type :color srcery, and it seems to change the color scheme correctly.  Since I want srcery to be my default color scheme, I put `colorscheme srcery` in my .vimrc file.  I save and quit.  When I reopen the file I am presented with the error. 

Thanks for any help.

**Comment by roosta** [comment]
Hi, glad you like the colorscheme :) My initial guess as to why you get that error message is that maybe your setting the `colorscheme srcery` option before vim-plug init? It should be after, like this:
```viml
call plug#begin('~/.vim/plugged')
Plug 'srcery-colors/srcery-vim'
call plug#end() 
colorscheme srcery
```

**Comment by ngc2392** [comment]
Yep, that was the problem.  Sorry for such a stupid mistake but thank you for the help!

**Comment by roosta** [comment]
Glad I could help!
