### ISSUE TITLE
Gray color is unclear with black terminal background

### ISSUE THREAD

**Issue by vsmysle** [srcery-colors/srcery-vim#46]
Hello!
Thank you for such a wonderful colorscheme!

After the last commits I have encountered with a small issue:
Sections like inline comments, shebangs, etc. in the source code looks too dark to my eyes.

**Examples:**
![image](https://user-images.githubusercontent.com/21976494/72640077-cf485a80-396f-11ea-8f19-a2bbd73aded8.png)
![image](https://user-images.githubusercontent.com/21976494/72640344-5b5a8200-3970-11ea-93b7-591d3bd10ea5.png)
![image](https://user-images.githubusercontent.com/21976494/72640406-7f1dc800-3970-11ea-9223-37d59eb5cc9d.png)

**Environment:** 
Editor: NeoVIM: v0.4.3.
Terminal: kitty v0.14.2

Not sure that this is an issue for a lot of people but for me it is crucial.
May you please tell me how I can fix this?
Thanks for reading!

**Comment by MindTooth** [comment]
Do you have the colors set in kitty?  I believe them got updated as well.

<- macOS, kitty, vim and no issue.
<img width="697" alt="Screenshot 2020-01-17 at 20 44 40" src="https://user-images.githubusercontent.com/33870508/72641346-3cf18800-396a-11ea-9cc0-4f2d1ead06e2.png">

**Comment by vsmysle** [comment]
@MindTooth Damn, yes, I forgot to update them in kitty. Updated them and it looks readable now.
Thanks a lot for your help!
