### ISSUE TITLE
Tag latest release and upload to vim.org

### ISSUE THREAD

**Issue by roosta** [srcery-colors/srcery-vim#51]
Not sure how many people use that site for plugins anymore, but might be worth drafting a new version and uploading it. Haven't done so in ages.

**Comment by MindTooth** [comment]
Absolutely. 👍🏻  We should acknowledge that people use Vim differently.

**Comment by roosta** [comment]
I was about to tag the latest commit, when I began thinking about which version number we should use. I say we go for a a v1.0.0 release at this point, lots of changes since the last tag (v0.10.0) and I feel srcery is pretty stable as is. What do you think @MindTooth?

**Comment by MindTooth** [comment]
Yeah.

One thing though, maybe the options flags needs looking at.  See if anything is obsolete, needs changing, or just overall improve the documentation.  Many of the options I don't know what does.  And those I use, I don't fully understand. 😝  E.g. the transparent option and my struggles with Clap.

What I mean to say that maybe we need to look over the code one more time to look for any improvements to documentation or other abnormalities.  Not so say that it is lacking today, but just as a precaution and quality measurement.   Especially if we are to tag a 1.x release and submitting it to vim.org.

Thoughts?

**Comment by roosta** [comment]
Absolutely agree, I'll start going over the code, and I'll submit the changes of any are needed. For starters maybe the `srcery_transparent_background` should be renamed to something like `srcery_background_passthrough` to make it more clear what it does. 
Another change that might be good for a 1.0.0 release is to make all the colors configurable with variables, so that people can override whatever they want (https://github.com/srcery-colors/srcery-vim/issues/41)

**Comment by roosta** [comment]
I went over the options, and renamed srcery_background_passthrough. I'd leave the other options, since they all have their uses. You say there are opts you don't know what it does, could you be more specific? I'll try to update the readme/help file

**Comment by MindTooth** [comment]
I think mostly the inverse parts.  But I can’t really remember for sure.  Long time ago I posted. 😅

**Comment by roosta** [comment]
It's just controlling if you should use inverse colors for certain parts, foreground becomes background, and vise versa. It makes certain things stand out more, like search matches, and parenthesis matching, stuff like that. I can try rewriting some of the explanations. 

Yeah, been a while since I opened this, but I'm getting closer to a v1 release :)

**Comment by roosta** [comment]
@MindTooth can you think of anything else that should be done before uploading to vim.org?
Also, check out [this](https://github.com/srcery-colors/srcery-vim/commit/fad0ab556076f674a9450043d2bd77db8543caae) commit, does it improve the descriptions at all you think?

**Comment by roosta** [comment]
Also [this](https://github.com/srcery-colors/srcery-vim/commit/9e652e2a2f8cdded914f3b96276a47dcb017e6bc) commit :D

**Comment by MindTooth** [comment]
Not sure what else would be suitable.  Tried reading vim.org or the manual, but could not find any specific section for submitting scripts.

**Comment by roosta** [comment]
There's an account section, I've already uploaded srcery a [few times](https://www.vim.org/scripts/script.php?script_id=5411): I'll take care of it once we're happy and version is tagged.

**Comment by roosta** [comment]
Seems I misunderstood you, but no not sure there are any docs for that. I usually just download an archive of the release and upload that.

**Comment by roosta** [comment]
https://www.vim.org/scripts/script.php?script_id=5411
