### ISSUE TITLE
Alternative to underlined text

### ISSUE THREAD

**Issue by VladimirMarkelov** [srcery-colors/srcery-vim#61]
Hi! A nice theme, thank you! 

I wanted to give it a try but I had an issue. By default, spelling errors are underlined with blue curly line(in my GUI frontend app it looks like a blue straight line), and it is hard to notice. At the same time, HTTP links with straight red underline were easy to see at a glance. 

I tried to disable underline with `g:srcery_underline = 0` but it made things much worse: it removed any signs of incorrect spelling.

As I see, the colorscheme marks all spelling errors with `call s:HL('SpellBad',   s:none, s:none, s:undercurl, s:blue)`, in case of disabled underline it becomes `call s:HL('SpellBad',   s:none, s:none, "", s:blue)`. Could you add an alternative way to highlight spelling errors?

**Comment by roosta** [comment]
Hi, glad you like srcery :) 
That's unfortunate, maybe I could setup some sort of fallback when those two are disabled. What would you suggest as an alternate highlight?

**Comment by VladimirMarkelov** [comment]
It is hard to tell :)

E.g, in gruvbox they added an option how to override disabled underline, so spelling errors can look like just like regular errors. I'm talking about https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_guisp_fallback

**Comment by roosta** [comment]
I've created a branch with fallback highlighting, check it out and let me know if this works for you https://github.com/srcery-colors/srcery-vim/pull/62

**Comment by VladimirMarkelov** [comment]
Thank you! Now it is easy to notice(with fallback=bg). Though, it needs some time to test it thoroughly :)

**Comment by roosta** [comment]
no problem, I'll hold of merging #62  for a little while and let you test out properly. Please keep me posted if there is any issues.

**Comment by VladimirMarkelov** [comment]
Fell free to merge it as it works fine. 

My bad, it was bad wording. I meant the following: the previous colorscheme displayed spelling errors with red background, now it with a blue one. I understand that it depends on the selected colorscheme, but it needs some time for brains to switch to the new coloring scheme :)
