### ISSUE TITLE
README bug

### ISSUE THREAD

**Issue by VillagerTom** [srcery-colors/srcery-vim#79]
The directory of Vim 8's native support for plugins should be `~/.vim/pack` instead of `~/.vim/plug`. Please correct it in the README.

**Comment by MindTooth** [comment]
Hi.

You are free to open a MR with the corrections.  If not, I’ll take a look this weekend.

Thanks for the report. 👍🏻

**Comment by VillagerTom** [comment]
I'd like to help but, I'm not familiar with GitHub operations. So... sorry about taking your minute of the happy weekend relaxation😂.

"Birger J. Nordølum" ***@***.***>编写：
