### ISSUE TITLE
Manual install?

### ISSUE THREAD

**Issue by nanaya** [srcery-colors/srcery-vim#89]
I assume [manual install](https://github.com/srcery-colors/srcery-vim#manually) is no longer supported? I'm getting a bunch of undefined variable errors on startup.

**Comment by MindTooth** [comment]
Hi @nanaya.

I'm sorry to hear that the recent commit affected your setup.  We are trying to find a proper solution for this.

---

I assume that you refer to just putting `srcery.vim` inside `~/.vim/colors`?

I belive that the current code does not support this anymore and the use of the built-in package manager is needed.  Is that something that you are okay with, or would you only prefer the old method?

**Comment by nanaya** [comment]
No it's fine. I've updated my setup to use vim pack.

**Comment by MindTooth** [comment]
Good. :)  Thanks again.  We'll work on improving the documentation.
